add_lab("GaB")
add_lab_solution("GaB" ${CMAKE_CURRENT_LIST_DIR}/GaB.cu)
add_lab_solution("GaB_streaming" ${CMAKE_CURRENT_LIST_DIR}/GaB_streaming.cu)
add_lab_solution("GaB_batch" ${CMAKE_CURRENT_LIST_DIR}/GaB_batch.cu)
add_lab_solution("GaB_batch_streaming" ${CMAKE_CURRENT_LIST_DIR}/GaB_batch_streaming.cu)
add_lab_solution("GaB_constant_batch_streaming" ${CMAKE_CURRENT_LIST_DIR}/GaB_constant_batch_streaming.cu)
add_lab_solution("GaB_all_optimizations" ${CMAKE_CURRENT_LIST_DIR}/GaB_all_optimizations.cu)
